import Head from 'next/head';

const Header = () => (
  <Head>
    <title>Seth&apos;s Workshop</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/logo.png" />
  </Head>
)

export default Header